### ISSUE TITLE
Can you support block uploading of large files

### ISSUE THREAD

**Issue by winezer0** [caiguanhao/ossslim#1]
Can you support block uploading of large files ?

**Comment by caiguanhao** [comment]
Not now. You can use [github.com/aliyun/aliyun-oss-go-sdk](https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/oss/multipart.go)

**Comment by winezer0** [comment]
The  aliyun-oss-go-sdk  built-in breakpoint resume function doesn't seem to be working

Ossutil implements large file chunking and breakpoint continuation, but the code is complex.

ossslim is a good and can modification to do this
